services:
  mediaflow-proxy:
    ports:
      - "8888:8888"
environment:
      API_PASSWORD: mfp
      TRANSPORT_ROUTES: '{ "all://*.ichigotv.net": { "verify_ssl": false }, "all://ichigotv.net": { "verify_ssl": false } }'
    restart: always
    logging:
      options:
        max-size: 1g
    image: mhdzumair/mediaflow-proxy:latest
